apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::696066434799:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::696066434799:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-746B65QK0F0M
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-26T14:42:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1318"
  uid: f68c283f-f7b1-4440-892c-9985387db348
